name: kurly 
version: master
summary: kurly is an alternative to the widely popular curl program.
description: |
             kurly is designed to operate in a similar manner to curl, with select features. Notably, kurly is not aiming for feature parity, but common flags and mechanisms particularly within the HTTP(S) realm are to be expected.

confinement: strict

apps:
  kurly:
     command: kurly
     plugs: [network]
parts:
  kurly:
     source: . 
     plugin: go
     go-importpath: github.com/davidjpeacock/kurly
     
